server:
  port: 8081

spring:
  application:
    name: zelixa

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/shekza_db}
    username: ${DB_USERNAME:shekza_user}
    password: ${DB_PASSWORD:shekza_password}
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}




  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:noreply@zelixa.com}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  minio:
    url: ${MINIO_URL:http://localhost:9000}
    access-key: ${MINIO_ACCESS_KEY:minioadmin}
    secret-key: ${MINIO_SECRET_KEY:minioadmin}
    bucket: ${MINIO_BUCKET:shekza-bucket}

  rajaongkir:
    api-key: ${RAJAONGKIR_API_KEY:ff2e84e26f6372bc0f05af7d6a08b4c4}
    base-url: ${RAJAONGKIR_BASE_URL:https://rajaongkir.komerce.id/api/v1/calculate/domestic-cost}

  midtrans:
    merchant-id: ${MIDTRANS_MERCHANT_ID:G404512774}
    server-key: ${MIDTRANS_SERVER_KEY:SB-Mid-server-ZKLolOiZGtgd0ixvlEKjbZVb}
    client-key: ${MIDTRANS_CLIENT_KEY:SB-Mid-client-TujjGaeNHOZqNeQJ}
    is-production: ${MIDTRANS_IS_PRODUCTION:false}

  firebase:
    config-path: ${FIREBASE_CONFIG_PATH:firebase-service-account.json}


camunda:
  bpm:
    admin-user:
      id: admin
      password: ${CAMUNDA_ADMIN_PASSWORD:admin}
    filter:
      create: All Tasks
    database:
      type: postgres
      schema-update: true
    job-execution:
      enabled: true