# Removed obsolete version line

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://api.zelixa.my.id/api
        - NEXT_PUBLIC_STORAGE_URL=https://storage.zelixa.my.id
    container_name: zelixa-app
    restart: always
    ports:
      - "3012:3000"

    environment:
      # Database components for specific logic
      DB_USERNAME: rizaldi
      DB_PASSWORD: "15031996"
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: zelixa_db
      DATABASE_URL: postgresql://rizaldi:15031996@postgres:5432/zelixa_db
      NEXTAUTH_URL: https://zelixa.my.id
      NEXTAUTH_URL_INTERNAL: http://app:3000
      NEXTAUTH_SECRET: zelixa-key-2026-v1
      NEXTAUTH_TRUST_HOST: "true"
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: rizaldi
      MINIO_SECRET_KEY: 15031996
      MINIO_BUCKET: zelixa
      MINIO_USE_SSL: "false"

      NEXT_PUBLIC_MINIO_URL: https://storage.zelixa.my.id

    networks:
      - infra-network

networks:
  infra-network:
    external: true
